apiVersion: v1
kind: Secret
metadata:
  name: chatbot-api-secrets
type: Opaque
data:
  JWT_SECRET: {{ .Values.chatbotApi.secrets.jwtSecret | b64enc }}
  OPENAI_API_KEY: {{ .Values.chatbotApi.secrets.openaiKey | b64enc }}
  CHATBOT_SECRET: {{ .Values.chatbotApi.secrets.chatbotSecret | b64enc }}
  DATABASE_URL: {{ .Values.chatbotApi.secrets.databaseUrl | b64enc }}