apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-chatbot-api-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-chatbot-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3089
    