apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-message-archival-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Release.Name }}-message-archival-container
            image: {{ .Values.chatbotApi.image }}
            command: ["npm", "run", "archive", "--", "--th={{ .Values.chatbotApi.archivalThreshold }}"]
            env:
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: chatbot-api-secrets
                    key: DATABASE_URL
          restartPolicy: Never
