apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-pg
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-pg
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-pg-secret
                  key: pg_password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pg-pvc