apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-store-api-deployment
spec:
  replicas: {{ .Values.storeApi.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-store-api-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-store-api-app
    spec:
      containers:
      - name: {{ .Release.Name }}-store-api-container
        image: {{ .Values.storeApi.image }}
        ports:
          - containerPort: 3088
        env:
          - name: GOOGLE_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: store-api-config
                key: GOOGLE_CLIENT_ID
          - name: GOOGLE_REDIRECT_URI
            valueFrom:
              configMapKeyRef:
                name: store-api-config
                key: GOOGLE_REDIRECT_URI
          - name: APP_URL
            valueFrom:
              configMapKeyRef:
                name: store-api-config
                key: APP_URL
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: store-api-secrets
                key: JWT_SECRET
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: store-api-secrets
                key: GOOGLE_CLIENT_SECRET
          - name: WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                name: store-api-secrets
                key: WEBHOOK_SECRET
          - name: STRIPE_KEY
            valueFrom:
              secretKeyRef:
                name: store-api-secrets
                key: STRIPE_KEY
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: store-api-secrets
                key: DATABASE_URL
        resources:
          requests:
            memory: {{ .Values.storeApi.memoryRequest }}
            cpu: {{ .Values.storeApi.cpuRequest }}
          limits:
            memory: {{ .Values.storeApi.memoryLimit }}
            cpu: {{ .Values.storeApi.cpuLimit }}
