apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-store-db-migrate-job
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    spec:
      containers:
      - name: {{ .Release.Name }}-store-db-migrate-job-container
        image: {{ .Values.storeApi.image }}
        command: ["npm", "run", "{{ .Values.storeApi.migrateCommand }}"]
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: store-api-secrets
                key: DATABASE_URL
          - name: ADMIN_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: store-api-secrets
                key: ADMIN_USER_PASSWORD
      restartPolicy: Never
