apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-store-api-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-store-api-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3088
