apiVersion: v1
kind: Secret
metadata:
  name: store-api-secrets
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc }}
  ADMIN_USER_PASSWORD: {{ .Values.secrets.adminUserPassword | b64enc }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | b64enc }}
  WEBHOOK_SECRET: {{ .Values.secrets.webhookSecret | b64enc }}
  STRIPE_KEY: {{ .Values.secrets.stripeKey | b64enc }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | b64enc }}